apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-config
  namespace: targeting
data:
  TARGETING_POSTGRES_DB: targeting_db
  TARGETING_POSTGRES_USER: targeting_user
  APP_ENV: production
  APP_PORT: "8080"

