apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth
type: Opaque
stringData:
  AUTH_POSTGRES_DB: auth_db
  AUTH_POSTGRES_USER: auth_user
  AUTH_POSTGRES_PASSWORD: auth_password
  MASTER_KEY: admin-secreto-123

